use std::fs;
use std::path::Path;

fn main() {
    tauri_build::build();

    // Embed provider preset TOML files into the binary so they work
    // in both dev and production without filesystem path resolution.
    embed_presets();
}

fn embed_presets() {
    let presets_dir = Path::new("../resources/presets");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("embedded_presets.rs");

    let mut toml_files: Vec<String> = Vec::new();

    if let Ok(entries) = fs::read_dir(presets_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |ext| ext != "toml") {
                continue;
            }
            if let Ok(content) = fs::read_to_string(&path) {
                let name = path.file_stem().unwrap().to_string_lossy().to_string();
                toml_files.push(format!(
                    "(\"{name}\", r#\"{content}\"#),",
                ));
            }
        }
    }

    toml_files.sort();

    let generated = format!(
        "// Auto-generated by build.rs — DO NOT EDIT\n\
         // Embedded provider preset TOML files.\n\
         \n\
         pub const EMBEDDED_PRESET_TOMLS: &[(&str, &str)] = &[\n    {}\n];\n",
        toml_files.join("\n    ")
    );

    fs::write(&dest, generated).unwrap();
    println!("cargo:rerun-if-changed=../resources/presets");
}
